server:
  port: 8080
  servlet:
    context-path: /bootcamp

spring:
  datasource:
    url: jdbc:mysql://localhost/bootcamp_santander
    username: root
    password:

  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate: 
      ddl-auto: create-drop
